version: '3.9'

services:
  api:
    container_name: api
    build: 
      context: backend/.
    ports:
      - "8000:3000"
    volumes:
      - api:/usr/src/app
    networks:
      - transcendance

  frontend:
    container_name: front
    build:
      context: frontend/.
    ports:
      - "3001:3002"
    volumes:
      - front:/usr/src/app
    networks:
      - transcendance

  postgredb:
    container_name: postgredb
    build:
      context: db/.
    ports:
      - "???:???"
    volumes:
      - db:/usr/src/db
    networks:
      - transcendance
      
volumes:
  api:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "{$PWD}/backend/srcs"
  frontend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "{$PWD}/frontend/srcs"
  postgredb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "{$PWD}/postgredb/srcs"

networks:
  transcendance:
    driver: bridge
