version: '3.9'

services:
  api:
    container_name: api
    build: 
      context: backend/.
    ports:
      - "3000:3000"
    volumes:
      - api:/app
    networks:
      - transcendance
    env_file: .env
    depends_on:
      - postgredb

  frontend:
    container_name: front
    build:
      context: frontend/.
    ports:
      - "3002:3000"
    volumes:
      - frontend:/app
    networks:
      - transcendance
    env_file: .env
    depends_on:
      - api

  postgredb:
    image: postgres:latest
    container_name: postgredb
    volumes:
      - postgredb:/var/lib/postgresql/data
    networks:
      - transcendance
    env_file: .env
  
volumes:
  api:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "$PWD/backend/srcs"
  frontend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "$PWD/frontend/srcs"
  postgredb:

networks:
  transcendance:
    driver: bridge
