version: '3.9'

services:
  api:
    container_name: api
    build: 
      context: backend/.
    ports:
      - "8000:3000"
    volumes:
      - api:/app
    networks:
      - transcendance
    env_file: .env
    depends_on:
      - postgredb

  frontend:
    container_name: front
    build:
      context: frontend/.
    ports:
      - "3002:3000"
    volumes:
      - frontend:/app
    networks:
      - transcendance
    env_file: .env

  postgredb:
    container_name: postgredb
    build:
      context: postgredb/.
    ports:
      - "3001:5432"
    volumes:
      - postgredb:/app
    networks:
      - transcendance
    env_file: .env
  
volumes:
  api:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "$PWD/backend/srcs"
  frontend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "$PWD/frontend/srcs"
  postgredb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "$PWD/postgredb/srcs"

networks:
  transcendance:
    driver: bridge
